### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [BonsaiDen/gfm#1]
Personally, I would appreciate syntax highlighting on the source (Markdown)

i.e. http://codemirror.net/mode/gfm/index.html

The line numbers and the other basic features of CodeMirror might be useful too. You might appreciate the Vim bindings.

I can understand your motivation to limit dependencies and keep the editor simple but IMHO CodeMirror (or some alternative) is worth it.

Just a suggestion :)

**Comment by BonsaiDen** [comment]
I'll have a look into CodeMirror! :) Haven't look into code editors for quite in a while.

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
https://github.com/adobe/brackets/wiki/Notes-on-CodeMirror
https://github.com/adobe/brackets/wiki/CodeMirror-v3-integration

http://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_source_code_editors

**Comment by BonsaiDen** [comment]
http://bonsaiden.github.com/gfm/ added some initial integration. Also fixed the Firefox issues and updated style a bit. (make sure to hard refresh)

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
That was quick!

Looking pretty snazzy now.

I'm thinking this would be nice as an extension that clobbers GitHub's tabbed write/preview with this WYSIWYG UI.

Up until now I've been using http://dillinger.io but it's kind of over-engineered; all the meanwhile not producing proper GitHub-flavoured markup. I'm feeling the consistency and simplicity of this project :)

**Comment by BonsaiDen** [comment]
Thanks! I'll have a look at some GitHub integration tomorrow.
